site_name: Мой персональный сайт
site_description: Персональная страница обо мне
site_author: Саша
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share

nav:
  - Главная: index.md
  - О себе: about.md
  - Проекты: projects.md
  - Контакты: contacts.md
  - Резюме: resume.md
  - Достижения: achievements.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
  palette:
    - scheme: default        # светлая тема
      primary: indigo        # основной цвет
      accent: pink           # акцентный цвет
      toggle:
        icon: material/weather-night
        name: Темная тема
    - scheme: slate          # тёмная тема
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
  logo: images/logo.jpg
  favicon: images/favicon.jpg


copyright: "© 2025 Саша. Сделано на MkDocs + Material."

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sblrok03
    - icon: fontawesome/brands/telegram
      link: https://t.me/sblrok03
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sblrok03/
